* Vagrant setup for Clojure
Just updated the [[https://github.com/Seajure/emacs-clojure-vagrant][Seajure]] version.
** Setup
   - Vagrant [[http://vagrantup.com/docs/getting-started/index.html][Vagrant Getting Started]]
      - Install [[http://www.virtualbox.org/wiki/Downloads][VirtualBox 4.x]]
      - Install [[http://www.virtualbox.org/wiki/Downloads][VirtualBox Extension Pack (Same Page)]]
      - Install [[http://downloads.vagrantup.com/][Vagrant]]
      - =vagrant up= # inside the directory containing this readme
** Usage
   Once Vagrant provisions your VM, use =vagrant ssh= to log in. Your
   VM will have a Jark swank session running, so you can immediately
   start Emacs and do =M-x slime-connect= to port 4005. You can start
   a new project with =lein new myproject= or pull down an existing
   project to hack on via git.
** Contents
   - Emacs 24 (with starter kit 2 and relevant Clojure modes)
   - tmux (with better config)
   - [[http://github.com/technomancy/leiningen][Leiningen]]
   - [[http://icylisper.in/jark/][Jark]]
** Troubleshooting
   A standard Ubuntu 10.04 install (YMMV for other distros/versions) doesn't have the appropriate ruby setup and needs
   some additional =apt-get=-ing to install vagrant. Assuming only that VirtualBox is installed, the following additional
   steps need to be performed before you can run =gem install vagrant=:  
   - Run =sudo apt-get install rubygems1.8 ruby-dev libopenssl-ruby=
   - Next do a =sudo gem install rubygems-update= and =sudo /var/lib/gems/1.8/bin/update_rubygems= to get the latest rubygems
   At this point you should be able to do a =gem install vagrant= 
